name: Sync with Gitee

on:
  schedule:
    - cron: '*/5 * * * *' # 每天午夜（UTC时间）运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync with Gitee
      run: |
        git remote add gitee https://laohuang112:e2f2ab487540e79348d79db0d42ed0a5@gitee.com/hassiozh/addons.git
        git push --force gitee master
